export const NUMBERS = [
  { id: 0, 'sino': '영/공', native: '–' },
  { id: 1, 'sino': '일', native: '하나' },
  { id: 2, 'sino': '이', native: '둘' },
  { id: 3, 'sino': '삼', native: '셋' },
  { id: 4, 'sino': '사', native: '넷' },
  { id: 5, 'sino': '오', native: '다섯' },
  { id: 6, 'sino': '육', native: '여섯' },
  { id: 7, 'sino': '칠', native: '일곱' },
  { id: 8, 'sino': '팔', native: '여덟' },
  { id: 9, 'sino': '구', native: '아홉' },
  { id: 10, 'sino': '십', native: '열' },
  { id: 11, 'sino': '십일', native: '열 하나' },
  { id: 12, 'sino': '십이', native: '열 둘' },
  { id: 13, 'sino': '십삼', native: '열 셋' },
  { id: 14, 'sino': '십사', native: '열 넷' },
  { id: 15, 'sino': '십오', native: '열 다섯' },
  { id: 16, 'sino': '십육', native: '열 여섯' },
  { id: 17, 'sino': '십칠', native: '열 일곱' },
  { id: 18, 'sino': '십팔', native: '열 여덟' },
  { id: 19, 'sino': '십구', native: '열 아홉' },
  { id: 20, 'sino': '이십', native: '스물' },
  { id: 21, 'sino': '이십 일', native: '스물 하나' },
  { id: 22, 'sino': '이십 이', native: '스물 둘' },
  { id: 23, 'sino': '이십 삼', native: '스물 셋' },
  { id: 24, 'sino': '이십 사', native: '스물 넷' },
  { id: 25, 'sino': '이십 오', native: '스물 다섯' },
  { id: 26, 'sino': '이십 육', native: '스물 여섯' },
  { id: 27, 'sino': '이십 칠', native: '스물 일곱' },
  { id: 28, 'sino': '이십 팔', native: '스물 여덟' },
  { id: 29, 'sino': '이십 구', native: '스물 아홉' },
  { id: 30, 'sino': '삼십', native: '서른' },
  { id: 31, 'sino': '삼십 일', native: '서른 하나' },
  { id: 32, 'sino': '삼십 이', native: '서른 둘' },
  { id: 33, 'sino': '삼십 삼', native: '서른 셋' },
  { id: 34, 'sino': '삼십 사', native: '서른 넷' },
  { id: 35, 'sino': '삼십 오', native: '서른 다섯' },
  { id: 36, 'sino': '삼십 육', native: '서른 여섯' },
  { id: 37, 'sino': '삼십 칠', native: '서른 일곱' },
  { id: 38, 'sino': '삼십 팔', native: '서른 여덟' },
  { id: 39, 'sino': '삼십 구', native: '서른 아홉' },
  { id: 40, 'sino': '사십', native: '마흔' },
  { id: 41, 'sino': '사십 일', native: '마흔 하나' },
  { id: 42, 'sino': '사십 이', native: '마흔 둘' },
  { id: 43, 'sino': '사십 삼', native: '마흔 셋' },
  { id: 44, 'sino': '사십 사', native: '마흔 넷' },
  { id: 45, 'sino': '사십 오', native: '마흔 다섯' },
  { id: 46, 'sino': '사십 육', native: '마흔 여섯' },
  { id: 47, 'sino': '사십 칠', native: '마흔 일곱' },
  { id: 48, 'sino': '사십 팔', native: '마흔 여덟' },
  { id: 49, 'sino': '사십 구', native: '마흔 아홉' },
  { id: 50, 'sino': '오십', native: '쉰' },
  { id: 51, 'sino': '오십 일', native: '쉰 하나' },
  { id: 52, 'sino': '오십 이', native: '쉰 둘' },
  { id: 53, 'sino': '오십 삼', native: '쉰 셋' },
  { id: 54, 'sino': '오십 사', native: '쉰 넷' },
  { id: 55, 'sino': '오십 오', native: '쉰 다섯' },
  { id: 56, 'sino': '오십 육', native: '쉰 여섯' },
  { id: 57, 'sino': '오십 칠', native: '쉰 일곱' },
  { id: 58, 'sino': '오십 팔', native: '쉰 여덟' },
  { id: 59, 'sino': '오십 구', native: '쉰 아홉' },
  { id: 60, 'sino': '육십', native: '예순' },
  { id: 61, 'sino': '육십 일', native: '예순 하나' },
  { id: 62, 'sino': '육십 이', native: '예순 둘' },
  { id: 63, 'sino': '육십 삼', native: '예순 셋' },
  { id: 64, 'sino': '육십 사', native: '예순 넷' },
  { id: 65, 'sino': '육십 오', native: '예순 다섯' },
  { id: 66, 'sino': '육십 육', native: '예순 여섯' },
  { id: 67, 'sino': '육십 칠', native: '예순 일곱' },
  { id: 68, 'sino': '육십 팔', native: '예순 여덟' },
  { id: 69, 'sino': '육십 구', native: '예순 아홉' },
  { id: 70, 'sino': '칠십', native: '일흔' },
  { id: 71, 'sino': '칠십 일', native: '일흔 하나' },
  { id: 72, 'sino': '칠십 이', native: '일흔 둘' },
  { id: 73, 'sino': '칠십 삼', native: '일흔 셋' },
  { id: 74, 'sino': '칠십 사', native: '일흔 넷' },
  { id: 75, 'sino': '칠십 오', native: '일흔 다섯' },
  { id: 76, 'sino': '칠십 육', native: '일흔 여섯' },
  { id: 77, 'sino': '칠십 칠', native: '일흔 일곱' },
  { id: 78, 'sino': '칠십 팔', native: '일흔 여덟' },
  { id: 79, 'sino': '칠십 구', native: '일흔 아홉' },
  { id: 80, 'sino': '팔십', native: '여든' },
  { id: 81, 'sino': '팔십 일', native: '여든 하나' },
  { id: 82, 'sino': '팔십 이', native: '여든 둘' },
  { id: 83, 'sino': '팔십 삼', native: '여든 셋' },
  { id: 84, 'sino': '팔십 사', native: '여든 넷' },
  { id: 85, 'sino': '팔십 오', native: '여든 다섯' },
  { id: 86, 'sino': '팔십 육', native: '여든 여섯' },
  { id: 87, 'sino': '팔십 칠', native: '여든 일곱' },
  { id: 88, 'sino': '팔십 팔', native: '여든 여덟' },
  { id: 89, 'sino': '팔십 구', native: '여든 아홉' },
  { id: 90, 'sino': '구십', native: '아흔' },
  { id: 91, 'sino': '구십 일', native: '아흔 하나' },
  { id: 92, 'sino': '구십 이', native: '아흔 둘' },
  { id: 93, 'sino': '구십 삼', native: '아흔 셋' },
  { id: 94, 'sino': '구십 사', native: '아흔 넷' },
  { id: 95, 'sino': '구십 오', native: '아흔 다섯' },
  { id: 96, 'sino': '구십 육', native: '아흔 여섯' },
  { id: 97, 'sino': '구십 칠', native: '아흔 일곱' },
  { id: 98, 'sino': '구십 팔', native: '아흔 여덟' },
  { id: 99, 'sino': '구십 구', native: '아흔 아홉' },
  { id: 100, 'sino': '백', native: '–' }
];

export const MONTH_KR = [
  '일월',
  '이월',
  '삼월',
  '사월',
  '오월',
  '유월',
  '칠월',
  '팔월',
  '구월',
  '시월',
  '십일월',
  '십이월'
];

export const WEEKDAY_KR = [
  '일요일', // sunday
  '월요일',
  '화요일',
  '수요일',
  '목요일',
  '금요일',
  '토요일',
];

export const MONTH_EN = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
]

export const WEEKDAY_EN = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday"
]
