# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Heroku deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test --if-present
    - run: npm run build 
      
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.4
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.heroku_api_key }}
        # Email that you use with heroku
        heroku_email: ${{ secrets.heroku_email }}
        # The appname to use for deploying/updating
        heroku_app_name: svelte-korean-numbers
        # An optional buildpack to use when creating the heroku application
        #buildpack: # optional
        # The branch that you would like to deploy to Heroku
       # branch: # optional, default is HEAD
        # Set this to true if you don't want to use --force when switching branches
        #dontuseforce: # optional
        # Will deploy using Dockerfile in project root.
        usedocker: true # optional
        # Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled
        # docker_heroku_process_type: # optional, default is web
        # Set if your app is located in a subdirectory.
        # appdir: public # optional, default is 
